export type BibleBook = {
  name: string;
  id: string;
  chapters: number;
  testament: 'Old' | 'New';
};

export const BIBLE_BOOKS: BibleBook[] = [
  { name: 'Genesis', id: 'GEN', chapters: 50, testament: 'Old' },
  { name: 'Exodus', id: 'EXO', chapters: 40, testament: 'Old' },
  { name: 'Leviticus', id: 'LEV', chapters: 27, testament: 'Old' },
  { name: 'Numbers', id: 'NUM', chapters: 36, testament: 'Old' },
  { name: 'Deuteronomy', id: 'DEU', chapters: 34, testament: 'Old' },
  { name: 'Joshua', id: 'JOS', chapters: 24, testament: 'Old' },
  { name: 'Judges', id: 'JDG', chapters: 21, testament: 'Old' },
  { name: 'Ruth', id: 'RUT', chapters: 4, testament: 'Old' },
  { name: '1 Samuel', id: '1SA', chapters: 31, testament: 'Old' },
  { name: '2 Samuel', id: '2SA', chapters: 24, testament: 'Old' },
  { name: '1 Kings', id: '1KI', chapters: 22, testament: 'Old' },
  { name: '2 Kings', id: '2KI', chapters: 25, testament: 'Old' },
  { name: '1 Chronicles', id: '1CH', chapters: 29, testament: 'Old' },
  { name: '2 Chronicles', id: '2CH', chapters: 36, testament: 'Old' },
  { name: 'Ezra', id: 'EZR', chapters: 10, testament: 'Old' },
  { name: 'Nehemiah', id: 'NEH', chapters: 13, testament: 'Old' },
  { name: 'Esther', id: 'EST', chapters: 10, testament: 'Old' },
  { name: 'Job', id: 'JOB', chapters: 42, testament: 'Old' },
  { name: 'Psalms', id: 'PSA', chapters: 150, testament: 'Old' },
  { name: 'Proverbs', id: 'PRO', chapters: 31, testament: 'Old' },
  { name: 'Ecclesiastes', id: 'ECC', chapters: 12, testament: 'Old' },
  { name: 'Song of Solomon', id: 'SNG', chapters: 8, testament: 'Old' },
  { name: 'Isaiah', id: 'ISA', chapters: 66, testament: 'Old' },
  { name: 'Jeremiah', id: 'JER', chapters: 52, testament: 'Old' },
  { name: 'Lamentations', id: 'LAM', chapters: 5, testament: 'Old' },
  { name: 'Ezekiel', id: 'EZK', chapters: 48, testament: 'Old' },
  { name: 'Daniel', id: 'DAN', chapters: 12, testament: 'Old' },
  { name: 'Hosea', id: 'HOS', chapters: 14, testament: 'Old' },
  { name: 'Joel', id: 'JOL', chapters: 3, testament: 'Old' },
  { name: 'Amos', id: 'AMO', chapters: 9, testament: 'Old' },
  { name: 'Obadiah', id: 'OBA', chapters: 1, testament: 'Old' },
  { name: 'Jonah', id: 'JON', chapters: 4, testament: 'Old' },
  { name: 'Micah', id: 'MIC', chapters: 7, testament: 'Old' },
  { name: 'Nahum', id: 'NAM', chapters: 3, testament: 'Old' },
  { name: 'Habakkuk', id: 'HAB', chapters: 3, testament: 'Old' },
  { name: 'Zephaniah', id: 'ZEP', chapters: 3, testament: 'Old' },
  { name: 'Haggai', id: 'HAG', chapters: 2, testament: 'Old' },
  { name: 'Zechariah', id: 'ZEC', chapters: 14, testament: 'Old' },
  { name: 'Malachi', id: 'MAL', chapters: 4, testament: 'Old' },
  { name: 'Matthew', id: 'MAT', chapters: 28, testament: 'New' },
  { name: 'Mark', id: 'MRK', chapters: 16, testament: 'New' },
  { name: 'Luke', id: 'LUK', chapters: 24, testament: 'New' },
  { name: 'John', id: 'JHN', chapters: 21, testament: 'New' },
  { name: 'Acts', id: 'ACT', chapters: 28, testament: 'New' },
  { name: 'Romans', id: 'ROM', chapters: 16, testament: 'New' },
  { name: '1 Corinthians', id: '1CO', chapters: 16, testament: 'New' },
  { name: '2 Corinthians', id: '2CO', chapters: 13, testament: 'New' },
  { name: 'Galatians', id: 'GAL', chapters: 6, testament: 'New' },
  { name: 'Ephesians', id: 'EPH', chapters: 6, testament: 'New' },
  { name: 'Philippians', id: 'PHP', chapters: 4, testament: 'New' },
  { name: 'Colossians', id: 'COL', chapters: 4, testament: 'New' },
  { name: '1 Thessalonians', id: '1TH', chapters: 5, testament: 'New' },
  { name: '2 Thessalonians', id: '2TH', chapters: 3, testament: 'New' },
  { name: '1 Timothy', id: '1TI', chapters: 6, testament: 'New' },
  { name: '2 Timothy', id: '2TI', chapters: 4, testament: 'New' },
  { name: 'Titus', id: 'TIT', chapters: 3, testament: 'New' },
  { name: 'Philemon', id: 'PHM', chapters: 1, testament: 'New' },
  { name: 'Hebrews', id: 'HEB', chapters: 13, testament: 'New' },
  { name: 'James', id: 'JAS', chapters: 5, testament: 'New' },
  { name: '1 Peter', id: '1PE', chapters: 5, testament: 'New' },
  { name: '2 Peter', id: '2PE', chapters: 3, testament: 'New' },
  { name: '1 John', id: '1JN', chapters: 5, testament: 'New' },
  { name: '2 John', id: '2JN', chapters: 1, testament: 'New' },
  { name: '3 John', id: '3JN', chapters: 1, testament: 'New' },
  { name: 'Jude', id: 'JUD', chapters: 1, testament: 'New' },
  { name: 'Revelation', id: 'REV', chapters: 22, testament: 'New' },
];

export function getBibleBook(name: string): BibleBook | undefined {
  return BIBLE_BOOKS.find((book) => book.name.toLowerCase() === name.toLowerCase());
}
